name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run lint
        run: flake8 .

      - name: Run hand-written tests (unit only)
        run: PYTHONPATH=. pytest tests/ -m "not integration"

      - name: Generate tests with Pynguin
        run: |
          export PYNGUIN_DANGER_AWARE=1
          pynguin --project-path . --output-path generated-tests --module-name agent --maximum-search-time 60 --maximum-iterations 5000

      - name: Run Pynguin-generated tests
        run: PYTHONPATH=. pytest generated-tests/ -m "not integration" --ignore=generated-tests/test_safe_utils.py